### ISSUE TITLE
[Lemmy] Neonmodem won't show any posts on lemmy.world or feddit.de

### ISSUE THREAD

**Issue by superkret** [mrusme/neonmodem#60] opened 2024-05-17 19:13 UTC
Affected Version:  neonmodem_1.0.4_linux_amd64
Affected System: Debian Bookworm amd64
Steps to reproduce: 
- I downloaded  neonmodem_1.0.4_linux_amd64.tar.gz and unpacked it in /usr/local/bin
- I connected neonmodem with neonmodem connect --type lemmy --url https://lemmy.world
- I entered my username and password and verified they're correct in the config file
- I launched it with neonmodem
- Neonmodem launches but doesn't show any posts
- Same result when connecting to feddit.de instance
- debug log attached

[neonmodem.log](https://github.com/mrusme/neonmodem/files/15357284/neonmodem.log)

I suspect this has to do with the newest lemmy version v0.19.3, since the same bug is mentioned in issue #58 from April, but none prior to that.

**Comment by airblast-dev** [comment] 2024-05-18 15:58
Having the same problem as well. Installed from https://aur.archlinux.org/packages/neonmodem

**Comment by mrusme** [comment] 2024-05-19 18:43
This is odd. I tried reproducing this issue on SDF and I couldn't, despite the instance seemingly using the same lemmy version as lemmy.world. It appears that the cause/one of the causes might be some configuration with these specific instances in regards to the timestamps of posts:

```
2024-05-17T21:05:23.490+0200⇥ ERROR⇥aggregator/aggregator.go:77⇥aggregator error: parsing time "2024-05-17T19:04:47.410256Z": extra tex    t: "Z"
326
327 github.com/mrusme/neonmodem/aggregator.(*Aggregator).ListPosts
328 ⇥ /home/runner/work/neonmodem/neonmodem/aggregator/aggregator.go:77
329 github.com/mrusme/neonmodem/ui/views/posts.(*Model).refresh.func1
330 ⇥ /home/runner/work/neonmodem/neonmodem/ui/views/posts/posts.go:206
331 github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1
332 ⇥ /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:268
333 2024-05-17T21:05:23.490+0200⇥ ERROR⇥posts/posts.go:209⇥ [parsing time "2024-05-17T19:04:47.410256Z": extra text: "Z"]
334 github.com/mrusme/neonmodem/ui/views/posts.(*Model).refresh.func1
335 ⇥ /home/runner/work/neonmodem/neonmodem/ui/views/posts/posts.go:209
336 github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1
337 ⇥ /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:268
```

Will investigate further.

**Comment by mrusme** [comment] 2024-05-22 16:00
Just as a status update: I requested access to lemmy.world three days ago but I haven't received it yet. I will try with feddit.de now, just to have an account to reproduce this issue.

**Comment by superkret** [comment] 2024-05-28 16:35
I tried connecting with lemmy.sdf.org since you said you couldn't reproduce the issue with SDF.
Still nothing showing up, log attached.

Thanks for what you do!
[neonmodem.log](https://github.com/mrusme/neonmodem/files/15473128/neonmodem.log)

**Comment by mrusme** [comment] 2024-05-28 21:15
@superkret thank you for the log. Given that you seem to be having this issue even with SDF, I am somewhat confident that this issue has not been an issue anymore in the latest `master`. I hence published a [new release](https://github.com/mrusme/neonmodem/releases/tag/v1.0.5) and would be grateful if you would give it a try and report back on whether you still experience this problem.

**Comment by airblast-dev** [comment] 2024-05-29 21:00
Just downloaded the latest release, seems to be working! I have also marked the AUR package out-of-date, to avoid confusion.

**Comment by mrusme** [comment] 2024-06-09 23:15
I will close this issue. In case anyone experiences any more problems with Lemmy, feel free to reopen!

**Closed by mrusme** 2024-06-09 23:15 UTC
Labels: bug

**Comment by tuuktuuk** [comment] 2025-07-11 18:42
Seems that neonmodem from file neonmodem_1.0.7_linux_amd64.tar.gz is completely unable to connect to lemmy. The log file says the following:

```
{"level":"error","ts":1752259175.780681,"caller":"cmd/root.go:97","msg":"error loading system lemmy: 400 Bad Request: rate_limit_error","stacktrace":"github.com/mrusme/neonmodem/cmd.loadSystems\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:97\ngithub.com/mrusme/neonmodem/cmd.init.func1\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:124\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1019\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071\ngithub.com/mrusme/neonmodem/cmd.Execute\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:136\nmain.main\n\t/home/runner/work/neonmodem/neonmodem/neonmodem.go:13\nruntime.main\n\t/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.3.linux-amd64/src/runtime/proc.go:283"}
{"level":"info","ts":1752259175.780814,"caller":"cmd/root.go:98","msg":"system lemmy won't be available due to errors"}

```

**Comment by mrusme** [comment] 2025-07-12 00:22
That error message is just saying that errors happened while trying to load the Lemmy system and hence it won't be available. The error that happened, however, is the `400 Bad Request: rate_limit_error`.

This issue is specific to the instance configuration and there's not a lot that can be done from a user's perspective, apart from choosing an instance with more relaxed limits. From a developer's perspective there are multiple things that could be done:

- Decrease the `Limit` for e.g. `ListPosts` from `50` to e.g. `10`. This however would require finally implementing _lazy loading_, meaning that when a user scrolls past the 7th or so pre-loaded post, the Lemmy system should load the next batch of posts. The framework for this is not in place yet and is rather a complex undertaking.
- Throttling between individual calls could be implemented, which, however, would slow things down immensely and result in a pretty bad user experience.

Either way, this specic error is a new one and plays in a different ball park. If you're simply curious to try out Neon Modem I suggest picking a different instance with higher limits for the time being. If you're actively looking to use Neon Modem on either of the mentioned instances, I'd ask you to approach the instance admins and ask for the specifics of their rate limit configurations. In order to fix this I would need to know what numbers would be deemed _okay_ by instances, so I can plan the requests accordingly.

**Comment by mrusme** [comment] 2025-07-12 13:51
That is an interesting use case! Tbh, I have never tried NMO on a braille display, nor considered it to be an option, given the TUI trickery that I have to employ to _draw windows_ and things like that. Please let me know how it goes, as I am happy to improve on that!

From experience I can tell that https://lemmy.sdf.org doesn't appear to employ these limits and is a fairly kind community. You might want to give it a try and see how far you get with it.

I have created a dedicated issue for the lazy-loading [here](https://github.com/mrusme/neonmodem/issues/74). If you experience issues related to your use case you're welcome to open new issues.
